theme: jekyll-theme-minimal
title: Estudio de la huella de carbono por el transporte de libros
description: Esta web presenta los mapas resultado del estudio. 
logo: https://cabildo.grancanaria.com/documents/38405/122652/Logo-consejeria-cultura-peq.jpg/db8f003d-7d18-41f0-ad2b-00e05620bdfb?t=1651501293607
